### ISSUE TITLE
add jdk 21 support

### ISSUE THREAD

**Issue by damingerdai** [adoptium/containers#426] opened 2023-09-26 09:24 UTC
### Please add the exact image (with tag) that you are using

21

### Please add the version of Docker you are running

21

### What happened?

A bug happened!

**Comment by dodgex** [comment] 2023-09-26 11:35
duplicate of https://github.com/adoptium/containers/issues/424

also see the release checklist https://github.com/adoptium/adoptium/issues/248

**Closed** 2023-09-28 07:56 UTC
Labels: bug, duplicate
