### ISSUE TITLE
Missing Docker/Alpine images for ARM64

### ISSUE THREAD

**Issue by giftkugel** [adoptium/containers#178] opened 2022-03-31 08:05 UTC
I sadly recognized, that there are no ARM64 Docker images based on [Alpine](https://hub.docker.com/_/alpine) available. 😢 
Alpine itself provides images for ARM64.

Would like to use Temurin in Docker/Alpine on my Apple silicon CPU.

```bash
docker pull eclipse-temurin:17-jre-alpine
```

```bash
17-jre-alpine: Pulling from library/eclipse-temurin
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by gdams** [comment] 2022-04-07 12:27
duplicate of https://github.com/adoptium/containers/issues/158

**Closed by gdams** 2022-04-07 12:27 UTC
Labels: duplicate
