### ISSUE TITLE
No matching manifest for linux/arm64/v8 | Apple M1

### ISSUE THREAD

**Issue by bcarun** [adoptium/containers#213] opened 2022-05-20 15:19 UTC
Hi Adoptium Team,

Thanks for eclipse-temurin images in Docker Hub. 

We are using Mac M1 for development and AWS EC2 linux for deployments. We are trying to upgrade to Java 17 and tried changing docker file to use 

`docker pull eclipse-temurin:17-jre-alpine`

But, it doesn't seem to work on M1 Mac. Got error `No matching manifest for linux/arm64/v8`. Could you please support M1 as well.

Thank you!

**Comment by gdams** [comment] 2022-05-25 10:27
duplicate of https://github.com/adoptium/containers/issues/158

**Closed by gdams** 2022-05-25 10:27 UTC
Labels: duplicate
